apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pipelines-vote-ui
  name: pipelines-vote-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipelines-vote-ui
  template:
    metadata:
      labels:
        app: pipelines-vote-ui
    spec:
      containers:
        - image: quay.io/openshift-pipeline/vote-ui:latest
          imagePullPolicy: Always
          name: pipelines-vote-ui
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 9090
              protocol: TCP
          env:
            - name: VOTING_API_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: ui-config
                  key: VOTING_API_SERVICE_HOST
            - name: VOTING_API_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: ui-config
                  key: VOTING_API_SERVICE_PORT
